export const coaches = [
  {
    id: "1",
    name: "Sarah Mitchell",
    specialty: "Strength & Conditioning",
    experience: "8 years",
    rating: 4.9,
    reviews: 127,
    image: "/coaches/sarah.jpg",
    bio: "Former competitive powerlifter with a passion for helping clients build functional strength and confidence.",
    certifications: ["NSCA-CSCS", "Precision Nutrition L1", "FMS Certified"],
    availability: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    hourlyRate: 85,
  },
  {
    id: "2",
    name: "Marcus Chen",
    specialty: "Weight Loss & Nutrition",
    experience: "6 years",
    rating: 4.8,
    reviews: 94,
    image: "/coaches/marcus.jpg",
    bio: "Helped over 500 clients achieve sustainable weight loss through personalized nutrition and training plans.",
    certifications: ["ACE-CPT", "Precision Nutrition L2", "TRX Certified"],
    availability: ["Mon", "Wed", "Thu", "Sat"],
    hourlyRate: 75,
  },
  {
    id: "3",
    name: "Elena Rodriguez",
    specialty: "HIIT & Functional Training",
    experience: "5 years",
    rating: 4.9,
    reviews: 112,
    image: "/coaches/elena.jpg",
    bio: "High-energy coach specializing in efficient, results-driven workouts for busy professionals.",
    certifications: ["NASM-CPT", "CrossFit L2", "Kettlebell Specialist"],
    availability: ["Tue", "Wed", "Fri", "Sat", "Sun"],
    hourlyRate: 70,
  },
  {
    id: "4",
    name: "James Thompson",
    specialty: "Sports Performance",
    experience: "10 years",
    rating: 5.0,
    reviews: 89,
    image: "/coaches/james.jpg",
    bio: "Former D1 athlete and coach helping athletes of all levels maximize their performance potential.",
    certifications: ["CSCS", "USA Weightlifting L2", "Graston Certified"],
    availability: ["Mon", "Tue", "Thu", "Fri"],
    hourlyRate: 95,
  },
  {
    id: "5",
    name: "Aisha Patel",
    specialty: "Yoga & Mobility",
    experience: "7 years",
    rating: 4.9,
    reviews: 156,
    image: "/coaches/aisha.jpg",
    bio: "Combining traditional yoga with modern mobility science for improved movement and recovery.",
    certifications: ["RYT-500", "FRC Certified", "Massage Therapist"],
    availability: ["Mon", "Wed", "Thu", "Sat", "Sun"],
    hourlyRate: 65,
  },
  {
    id: "6",
    name: "David Kim",
    specialty: "Bodybuilding & Physique",
    experience: "9 years",
    rating: 4.8,
    reviews: 78,
    image: "/coaches/david.jpg",
    bio: "Competition prep specialist and natural bodybuilding coach with a scientific approach to training.",
    certifications: ["ISSA-CPT", "ISSN Sports Nutrition", "Contest Prep Coach"],
    availability: ["Tue", "Wed", "Thu", "Fri", "Sat"],
    hourlyRate: 90,
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Jennifer Walsh",
    avatar: "/testimonials/jennifer.jpg",
    role: "Lost 45 lbs",
    content: "Working with Marcus completely changed my relationship with food and fitness. The personalized approach made all the difference - I've kept the weight off for over a year now.",
    rating: 5,
    coach: "Marcus Chen",
  },
  {
    id: "2",
    name: "Robert Martinez",
    avatar: "/testimonials/robert.jpg",
    role: "Marathon Runner",
    content: "Sarah's strength program helped me finally break through my running plateau. My endurance and recovery have improved dramatically.",
    rating: 5,
    coach: "Sarah Mitchell",
  },
  {
    id: "3",
    name: "Amanda Foster",
    avatar: "/testimonials/amanda.jpg",
    role: "Busy Professional",
    content: "Elena's 30-minute HIIT sessions fit perfectly into my schedule. I'm in the best shape of my life despite working 60-hour weeks.",
    rating: 5,
    coach: "Elena Rodriguez",
  },
  {
    id: "4",
    name: "Michael Chang",
    avatar: "/testimonials/michael.jpg",
    role: "College Athlete",
    content: "James helped me earn a D1 scholarship. His sport-specific training and mental coaching were game-changers for my performance.",
    rating: 5,
    coach: "James Thompson",
  },
  {
    id: "5",
    name: "Lisa Nakamura",
    avatar: "/testimonials/lisa.jpg",
    role: "Chronic Pain Recovery",
    content: "After years of back pain, Aisha's mobility work gave me my life back. I can finally play with my kids without discomfort.",
    rating: 5,
    coach: "Aisha Patel",
  },
  {
    id: "6",
    name: "Tom Bradley",
    avatar: "/testimonials/tom.jpg",
    role: "First Competition",
    content: "David guided me through my first bodybuilding show. His attention to detail and constant support helped me place top 3.",
    rating: 5,
    coach: "David Kim",
  },
];

export const pricingPlans = [
  {
    id: "starter",
    name: "Starter",
    description: "Perfect for getting started with online coaching",
    price: 149,
    period: "month",
    features: [
      "2 video coaching sessions per month",
      "Personalized workout plan",
      "Basic nutrition guidelines",
      "Email support (48h response)",
      "Progress tracking app access",
    ],
    popular: false,
  },
  {
    id: "pro",
    name: "Pro",
    description: "Our most popular plan for serious results",
    price: 299,
    period: "month",
    features: [
      "4 video coaching sessions per month",
      "Custom training program",
      "Detailed macro-based nutrition plan",
      "Priority chat support",
      "Weekly check-ins & adjustments",
      "Video form reviews",
      "Access to workout library",
    ],
    popular: true,
  },
  {
    id: "elite",
    name: "Elite",
    description: "Maximum support for transformative results",
    price: 499,
    period: "month",
    features: [
      "Unlimited video coaching sessions",
      "Fully customized periodized program",
      "Complete nutrition coaching",
      "24/7 direct coach access",
      "Daily check-ins",
      "Supplement guidance",
      "Competition/photo shoot prep",
      "Quarterly body composition analysis",
    ],
    popular: false,
  },
];

export const timeSlots = [
  "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM",
  "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM",
  "6:00 PM", "7:00 PM", "8:00 PM",
];

export const features = [
  {
    title: "Personalized Programs",
    description: "Custom training and nutrition plans tailored to your goals, lifestyle, and fitness level.",
    icon: "target",
  },
  {
    title: "Expert Coaches",
    description: "Work with certified professionals who have helped hundreds achieve their fitness goals.",
    icon: "users",
  },
  {
    title: "Flexible Scheduling",
    description: "Book sessions at times that work for you, with easy rescheduling options.",
    icon: "calendar",
  },
  {
    title: "Progress Tracking",
    description: "Monitor your transformation with detailed metrics and visual progress reports.",
    icon: "chart",
  },
  {
    title: "Video Sessions",
    description: "High-quality 1-on-1 video calls for form checks, coaching, and accountability.",
    icon: "video",
  },
  {
    title: "Community Support",
    description: "Join a supportive community of like-minded individuals on their fitness journey.",
    icon: "heart",
  },
];
